name: Run Python Script

on:
  push:
    branches: [ main ]

# 🔐 RBAC PERMISSIONS
permissions:
  contents: read
  actions: read

jobs:
  run-script:
    if: github.actor == 'rajeshrajeshrajesh'

    runs-on: ubuntu-latest
    
    env:
      DATABRICKS_TOKEN: ${{ secrets.NEW_SAMPLE_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'



      - name: Run Python file
        run: |
          python test.py
